const TASKS = [
  "### `Main` page (70 points)",
  "",
  "= = =",
  "",
  `#### Markup validation - **+10**`,
  `- [✅] Markup is valid per <https://validator.w3.org/>. "Document checking completed. No errors or warnings to show." - full points. Warnings (no errors) - half points **+5**`,
  "- [✅] The header logo is built from text elements, the page contains exactly one `<h1>`, and a favicon is added **+5**",
  "",
  `#### Валидация разметки - **+10**`,
  `- [✅] Разметка валидна согласно <https://validator.w3.org/>. «Проверка документа завершена. Нет ошибок или предупреждений для отображения» — полные баллы. Предупреждения (без ошибок) — половина баллов **+5**`,
  "- [✅] Логотип в шапке состоит из текстовых элементов, на странице есть ровно один `<h1>`, добавлен фавикон **+5**",
  "",
  "= = =",
  "",
  `#### Layout matches the design - **+35**`,
  "- [✅] `<header>` block **+5**",
  "- [✅] `Not only` block **+5**",
  "- [✅] `About` block **+5**",
  "- [✅] `Our Friends` block **+5**",
  "- [✅] `Help` block **+5**",
  "- [✅] `In addition` block **+5**",
  "- [✅] `<footer>` block **+5**",
  "",
  `#### Верстка соответствует дизайну - **+35**`,
  "- [✅] Блок `<header>` **+5**",
  "- [✅] Блок `Not only` **+5**",
  "- [✅] Блок `About` **+5**",
  "- [✅] Блок `Our Friends` **+5**",
  "- [✅] Блок `Help` **+5**",
  "- [✅] Блок `In addition` **+5**",
  "- [✅] Блок `<footer>` **+5**",
  "",
  "= = =",
  "",
  `#### CSS requirements - **+15**`,
  "- [✅] The `Help` block is positioned using a grid layout (flexbox or grid) **+5**",
  `- [✅] When zooming out or widening the browser window (>1280px), the layout stays centered - it doesn't shift to the side or stretch to full width **+5**`,
  `- [✅] The background color stretches across the full page width **+5**`,
  "",
  `#### Требования к CSS - **+15**`,
  "- [✅] Блок `Help` размечен с использованием сетки (flexbox или grid) **+5**",
  `- [✅] При уменьшении масштаба или расширении окна браузера (>1280px) макет остается центрированным — не смещается в сторону и не растягивается на всю ширину **+5**`,
  `- [✅] Фоновый цвет растягивается на всю ширину страницы **+5**`,
  "",
  "= = =",
  "",
  `#### Interactivity - **+10**`,
  "- [✅] The `About the Shelter` navigation item is highlighted and non-interactive; the other navigation items are interactive; smooth anchor scrolling works; and all page links behave per the [Page links and navigation](https://github.com/rolling-scopes-school/tasks/blob/master/stage0.5%20Bootcamp/tasks/shelter/shelter-part1.md#on-the-main-page) section **+5**",
  "- [✅] Each pet card in **Our Friends** is interactive when hovering over any area of the card; links and buttons have hover/active styling beyond `cursor: pointer` (color/background change); visual changes are smooth and do not affect neighboring elements **+5**",
  "",
  `#### Интерактивность - **+10**`,
  "- [✅] Пункт навигации `About the Shelter` подсвечен и не интерактивен; остальные пункты навигации интерактивны; работает плавная прокрутка по якорям; все ссылки на странице ведут себя согласно разделу [Ссылки и навигация по странице](https://github.com/rolling-scopes-school/tasks/blob/master/stage0.5%20Bootcamp/tasks/shelter/shelter-part1.md#on-the-main-page) **+5**",
  "- [✅] Каждая карточка питомца в блоке **Our Friends** интерактивна при наведении на любую область карточки; ссылки и кнопки имеют стилизацию при наведении/активации помимо `cursor: pointer` (изменение цвета/фона); визуальные изменения плавные и не влияют на соседние элементы **+5**",
  "",
  "= = =",
  "",
  "### `Pets` page (40 points)",
  "",
  "= = =",
  "",
  `- [✅] Markup validation - **+10**`,
  `#### Markup validation - **+10**`,
  "- [✅] Markup is valid per <https://validator.w3.org/> (same rules as for `Main`) **+5**",
  "- [✅] The header logo is built from text elements, the page contains exactly one `<h1>`, and a favicon is added **+5**",
  "",
  `#### Валидация разметки - **+10**`,
  "- [✅] Разметка валидна согласно <https://validator.w3.org/> (те же правила, что и для `Главной`) **+5**",
  "- [✅] Логотип в шапке состоит из текстовых элементов, на странице есть ровно один `<h1>`, добавлен фавикон **+5**",
  `- [✅] Layout matches the design - **+15**`,
  "",
  "= = =",
  "",
  `#### Layout matches the design - **+15**`,
  "- [✅] `<header>` block **+5**",
  "- [✅] `Our Friends` block **+5**",
  "- [✅] `<footer>` block **+5**",
  "",
  `#### Верстка соответствует дизайну - **+15**`,
  "- [✅] Блок `<header>` **+5**",
  "- [✅] Блок `Our Friends` **+5**",
  "- [✅] Блок `<footer>` **+5**",
  "",
  "= = =",
  "",
  `#### CSS requirements - **+5**`,
  `- [✅] When zooming out or widening the browser window (>1280px), the layout stays centered, and the background color stretches across the full page width **+5**`,
  "",
  `#### Требования к CSS - **+5**`,
  `- [✅] При уменьшении масштаба или расширении окна браузера (>1280px) макет остается центрированным, а фоновый цвет растягивается на всю ширину страницы **+5**`,
  "",
  "= = =",
  "",
  `#### Interactivity - **+10**`,
  "- [✅] The `Our pets` navigation item is highlighted and non-interactive; the other navigation items are interactive; pagination buttons show correct enabled/disabled state; smooth anchor scrolling works; and all page links behave per the [Page links and navigation](https://github.com/rolling-scopes-school/tasks/blob/master/stage0.5%20Bootcamp/tasks/shelter/shelter-part1.md#on-the-main-page) section **+5**",
  "- [✅] Each pet card in **Our Friends** is interactive when hovering over any area of the card; links and buttons have hover/active styling beyond `cursor: pointer`; visual changes are smooth and do not affect neighboring elements **+5**",
  "",
  `#### Интерактивность - **+10**`,
  "- [✅] Пункт навигации `Our pets` подсвечен и не интерактивен; остальные пункты навигации интерактивны; кнопки пагинации отображают корректное состояние (активно/неактивно); работает плавная прокрутка по якорям; все ссылки на странице ведут себя согласно разделу [Ссылки и навигация по странице](https://github.com/rolling-scopes-school/tasks/blob/master/stage0.5%20Bootcamp/tasks/shelter/shelter-part1.md#on-the-main-page) **+5**",
  "- [✅] Каждая карточка питомца в блоке **Our Friends** интерактивна при наведении на любую область карточки; ссылки и кнопки имеют стилизацию при наведении/активации помимо `cursor: pointer`; визуальные изменения плавные и не влияют на соседние элементы **+5**",
];

console.log(TASKS.join("\n"));
